import Head from 'next/head'
import Link from 'next/link'
import { Button } from 'react-bootstrap'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Innovage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1 className="display-1">Innovage</h1>
        <p>Sign in as:</p>
        <div className="d-flex flex-column align-items-center justify-content-center gap-3">
          <Link href="/client/signin">
            <Button className="w-100 px-5 py-2">Client</Button>
          </Link>
          <Link href="/banker/signin">
            <Button className="w-100">Banker</Button>
          </Link>
        </div>
      </div>
    </div>
  )
}
